export const home = document.querySelector("li:nth-child(1)")
export const oUniverso = document.querySelector("li:nth-child(2)")
export const explorar = document.querySelector("li:nth-child(3)")
export const BackgroundScreen = document.querySelector("body")
// export const navLink1 = document.querySelector("li:nth-child(1) a")
// export const navLink2 = document.querySelector("li:nth-child(2) a")
// export const navLink3 = document.querySelector("li:nth-child(3) a")