export const plantButton = document.querySelector(".plantButton")
export const cloudButton = document.querySelector(".cloudButton")
export const coffeeButton = document.querySelector(".coffeeButton")
export const campfireButton = document.querySelector(".campfireButton")
export let musicPlayer = document.querySelector(".musicPlayer")